baseURL = "/"
languageCode = "en-us"
title = "Sri Aspari"
metadataformat = "yaml"

PygmentsCodeFences = true
pygmentsUseClasses=true
# PygmentsStyle      = "monokai"

[params]
    name = "Sri Aspari"
    professional = "Wanna be a Web Developer"
    talkyardServerUrl = "https://comments-for-siarie-me.talkyard.net"
    talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[params.social]
    # a-facebook = "//facebook.com/ari.aspari"
    b-twitter  = "//twitter.com/siarie_"
    c-github   = "//github.com/siarie"
    d-send = "//t.me/siarie"
    e-mail   = "mailto:sriaspari@gmail.com"
    # f-rss     = "/rss.xml"


[permalinks]
    blog = "story/:filename/"
    # pages = "/:filename.html"


[menu]
    # [[menu.main]]
    #     name    = "home"
    #     pre     = "home"
    #     url     = "/"
    #     weight  = 1
    [[menu.main]]
        name    = "story"
        pre     = "story"
        url     = "/story/"
        weight  = 2

    # [[menu.main]]
    #     name    = "portofolio"
    #     pre     = "portofolio"
    #     url     = "/portofolio/"
    #     weight  = 3

    [[menu.main]]
        name    = "about"
        pre     = "about"
        url     = "/about/"
        weight  = 3
    [[menu.main]]
        name    = "Friends"
        pre     = "friends"
        url     = "/friends/"
        weight  = 4
