baseURL = "/"
languageCode = "en-us"
title = "Sri Aspari"
metadataformat = "yaml"

disqusShortname = "siarie"

PygmentsCodeFences = true
pygmentsUseClasses=true
# PygmentsStyle      = "monokai"

[params]
    author = "Sri Aspari"
    description = "Siarie's Portofolio and Personal Blog"
    professional = "Wanna be a Web Developer"

[params.social]
    # a-facebook = "//facebook.com/ari.aspari"
    b-twitter  = "//twitter.com/siarie_"
    c-github   = "//github.com/siarie"
    d-send = "//t.me/siarie"
    e-mail   = "mailto:mail@siarie.me"
    # f-rss     = "/rss.xml"


[permalinks]
    blog = "story/:filename/"
    # pages = "/:filename.html"


[menu]
    [[menu.main]]
        name    = "story"
        pre     = "story"
        url     = "/story/"
        weight  = 2

    [[menu.main]]
        name    = "portofolio"
        pre     = "portofolio"
        url     = "/portofolio/"
        weight  = 3

    [[menu.main]]
        name    = "about"
        pre     = "about"
        url     = "/about/"
        weight  = 3
    [[menu.main]]
        name    = "Friends"
        pre     = "friends"
        url     = "/friends/"
        weight  = 4
